FROM python:3.11-slim-bookworm
WORKDIR /opt/medusa/python
COPY src/python/ .
RUN pip install --no-cache-dir -e ".[dev]"
EXPOSE 8888
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
